<?php

namespace FMTCco\Integrations\Apis\Skimlinks\Requests;


/**
 * Class GetCommissionsHistory
 * @see     https://api-reports.skimlinks.com/doc/#reportcommissionshistory
 * @package App\Toolkit\NetworkConnections\Apis\Skimlinks\Requests
 */
class GetCommissionsHistory implements \JsonSerializable
{

    /**
     * Required. ISO 8601 timestamp
     * @var string
     */
    protected $endEventTime;

    /**
     * Required. ISO 8601 timestamp
     * @var string
     */
    protected $startEventTime;

    /**
     * List only a single commission with the given ID
     * @var int|null
     */
    protected $commissionID;

    /**
     * The date at which to begin the commission report - YYYY-mm-dd
     * @var string|null
     */
    protected $startDate;

    /**
     * The date at which to end the commission report - YYYY-mm-dd
     * @var string|null
     */
    protected $endDate;

    /**
     * List only commissions generated by a specific domain
     * @var int|null
     */
    protected $domainID;

    /**
     * The format of the response either xml or json.
     * Default value is xml.
     * @var string
     */
    protected $format               = 'json';

    /**
     * The unique event ID at which to end the report
     * @var int|null
     */
    protected $endEventID;

    /**
     * The unique event ID at which to begin the report
     * @var int|null
     */
    protected $startEventID;

    /**
     * List only commissions with a specific custom ID (an ID given by the publisher to mark a commission).
     * Known as xcust in Link API
     * @var string|null
     */
    protected $customID;

    /**
     * If you are a SkimBox user with a previously created API key, you may choose to report the commissions associated with one of the multiple publishers created using the SkimBox API.
     * In this case, your publisher ID will be the first part of the Skimlinks publisher ID
     * @var int|null
     */
    protected $publisherID;

    /**
     * Optional. Either import, update or cancel
     * @var string|null
     */
    protected $event;


    /**
     * @return array
     */
    public function jsonSerialize()
    {
        $object['endEventTime']             = $this->endEventTime;
        $object['startEventTime']           = $this->startEventTime;
        $object['commissionID']             = $this->commissionID;
        $object['startDate']                = $this->startDate;
        $object['endDate']                  = $this->endDate;
        $object['domainID']                 = $this->domainID;
        $object['format']                   = $this->format;
        $object['endEventID']               = $this->endEventID;
        $object['startEventID']             = $this->startEventID;
        $object['customID']                 = $this->customID;
        $object['publisherID']              = $this->publisherID;
        $object['event']                    = $this->event;

        return $object;
    }

    /**
     * @return string
     */
    public function getEndEventTime()
    {
        return $this->endEventTime;
    }

    /**
     * @param string $endEventTime
     */
    public function setEndEventTime($endEventTime)
    {
        $this->endEventTime = $endEventTime;
    }

    /**
     * @return string
     */
    public function getStartEventTime()
    {
        return $this->startEventTime;
    }

    /**
     * @param string $startEventTime
     */
    public function setStartEventTime($startEventTime)
    {
        $this->startEventTime = $startEventTime;
    }

    /**
     * @return int|null
     */
    public function getCommissionID()
    {
        return $this->commissionID;
    }

    /**
     * @param int|null $commissionID
     */
    public function setCommissionID($commissionID)
    {
        $this->commissionID = $commissionID;
    }

    /**
     * @return null|string
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * @param null|string $startDate
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;
    }

    /**
     * @return null|string
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * @param null|string $endDate
     */
    public function setEndDate($endDate)
    {
        $this->endDate = $endDate;
    }

    /**
     * @return int|null
     */
    public function getDomainID()
    {
        return $this->domainID;
    }

    /**
     * @param int|null $domainID
     */
    public function setDomainID($domainID)
    {
        $this->domainID = $domainID;
    }

    /**
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * @param string $format
     */
    public function setFormat($format)
    {
        $this->format = $format;
    }

    /**
     * @return int|null
     */
    public function getEndEventID()
    {
        return $this->endEventID;
    }

    /**
     * @param int|null $endEventID
     */
    public function setEndEventID($endEventID)
    {
        $this->endEventID = $endEventID;
    }

    /**
     * @return int|null
     */
    public function getStartEventID()
    {
        return $this->startEventID;
    }

    /**
     * @param int|null $startEventID
     */
    public function setStartEventID($startEventID)
    {
        $this->startEventID = $startEventID;
    }

    /**
     * @return null|string
     */
    public function getCustomID()
    {
        return $this->customID;
    }

    /**
     * @param null|string $customID
     */
    public function setCustomID($customID)
    {
        $this->customID = $customID;
    }

    /**
     * @return int|null
     */
    public function getPublisherID()
    {
        return $this->publisherID;
    }

    /**
     * @param int|null $publisherID
     */
    public function setPublisherID($publisherID)
    {
        $this->publisherID = $publisherID;
    }

    /**
     * @return null|string
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * @param null|string $event
     */
    public function setEvent($event)
    {
        $this->event = $event;
    }

}
