<?php

namespace FMTCco\Integrations\Apis\Skimlinks\Requests;


use FMTCco\Integrations\Traits\SimpleSerializable;

/**
 * Class GetReportMerchants
 * @see     https://api-reports.skimlinks.com/doc/#reportmerchants
 * @package App\Toolkit\NetworkConnections\Apis\Skimlinks\Requests
 */
class GetReportMerchants implements \JsonSerializable
{

    use SimpleSerializable;


    /**
     * Required
     * The date at which to end the commission report - YYYY-mm-dd
     * @var string
     */
    protected $endDate;

    /**
     * Required
     * The date at which to begin the commission report - YYYY-mm-dd
     * Minimum date - 2011-12-01
     * @var string
     */
    protected $startDate;

    /**
     * How to order the returned results. Parameter must be formatted in the following way
     * field|direction, field|direction,field2|direction2, etc
     * The following fields are valid:  clicks,totalCommission,ecpc,conversionRate,sales,merchantName
     * The following directions are valid: ascending,descending
     * @var string|null
     */
    protected $orderBy;

    /**
     * The product type you would like to narrow the results down to
     * Can be one of skimlinks, skimwords, showcases or all
     * It also accepts multiple products seperated by commas, e.g. skimlinks,skimwords.
     * Default is skimlinks
     * @var string|null
     */
    protected $product;


    /**
     * List only commissions generated by a specific domain.
     * @var int|null
     */
    protected $domainID;

    /**
     * @var string|null
     */
    protected $merchantName;

    /**
     * The format of the response either xml or json.
     * Default value is xml.
     * @var string
     */
    protected $format               = 'json';

    /**
     * What row to begin returning results from (default 0)
     * @var int
     */
    protected $responseFrom         = 0;

    /**
     * How many results to return (maximum 100) (default 100)
     * @var int
     */
    protected $responseLimit        = 100;

    /**
     * @var int|null
     */
    protected $publisherID;

    /**
     * @var int|null
     */
    protected $merchantID;


    /**
     * @return string
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * @param string $endDate
     */
    public function setEndDate($endDate)
    {
        $this->endDate = $endDate;
    }

    /**
     * @return string
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * @param string $startDate
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;
    }

    /**
     * @return null|string
     */
    public function getOrderBy()
    {
        return $this->orderBy;
    }

    /**
     * @param null|string $orderBy
     */
    public function setOrderBy($orderBy)
    {
        $this->orderBy = $orderBy;
    }

    /**
     * @return null|string
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * @param null|string $product
     */
    public function setProduct($product)
    {
        $this->product = $product;
    }

    /**
     * @return int|null
     */
    public function getDomainID()
    {
        return $this->domainID;
    }

    /**
     * @param int|null $domainID
     */
    public function setDomainID($domainID)
    {
        $this->domainID = $domainID;
    }

    /**
     * @return null|string
     */
    public function getMerchantName()
    {
        return $this->merchantName;
    }

    /**
     * @param null|string $merchantName
     */
    public function setMerchantName($merchantName)
    {
        $this->merchantName = $merchantName;
    }

    /**
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * @param string $format
     */
    public function setFormat($format)
    {
        $this->format = $format;
    }

    /**
     * @return int
     */
    public function getResponseFrom()
    {
        return $this->responseFrom;
    }

    /**
     * @param int $responseFrom
     */
    public function setResponseFrom($responseFrom)
    {
        $this->responseFrom = $responseFrom;
    }

    /**
     * @return int
     */
    public function getResponseLimit()
    {
        return $this->responseLimit;
    }

    /**
     * @param int $responseLimit
     */
    public function setResponseLimit($responseLimit)
    {
        $this->responseLimit = $responseLimit;
    }

    /**
     * @return int|null
     */
    public function getPublisherID()
    {
        return $this->publisherID;
    }

    /**
     * @param int|null $publisherID
     */
    public function setPublisherID($publisherID)
    {
        $this->publisherID = $publisherID;
    }

    /**
     * @return int|null
     */
    public function getMerchantID()
    {
        return $this->merchantID;
    }

    /**
     * @param int|null $merchantID
     */
    public function setMerchantID($merchantID)
    {
        $this->merchantID = $merchantID;
    }

}